apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
    component: cache
type: Opaque
data:
  # Base64 encoded values
  # redis123 (change this in production)
  REDIS_PASSWORD: cmVkaXMxMjM=
