apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    component: database
data:
  POSTGRES_DB: "myapp"
  postgresql.conf: |
    # PostgreSQL 15 configuration
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 4MB
    min_wal_size = 1GB
    max_wal_size = 4GB
    max_worker_processes = 8
    max_parallel_workers_per_gather = 2
    max_parallel_workers = 8
    max_parallel_maintenance_workers = 2

    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_min_duration_statement = 1000
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

    # Security and authentication
    password_encryption = scram-sha-256
    ssl = off

    # Memory settings (adjust based on available resources)
    shared_preload_libraries = 'pg_stat_statements'

  init.sql: |
    -- Initial database setup
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

    -- Create application user (if needed)
    -- CREATE USER appuser WITH PASSWORD 'changeme';
    -- GRANT ALL PRIVILEGES ON DATABASE myapp TO appuser;
