apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: development
spec:
  rules:
  - host: "backend.127.0.0.1.sslip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dev-backend-service
            port:
              number: 80
  - host: "frontend.127.0.0.1.sslip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dev-frontend-service
            port:
              number: 80
